host:
  # 下方 local 測試參數，產線使用 heroku 使用 os.Getenv("PORT") 取環境變數方式
  limiter: 8080
  # mode: counter(計數器)、tokenBucket(令牌桶)、redisCounter(計數器 Redis)
  mode: redisCounter
  interval: 60
  maxCount: 60

gin:
  # mode: debug、release、test
  mode: debug

# 下方 local 測試參數，產線使用 heroku 使用 os.Getenv("REDIS_URL") 取環境變數方式
redis:
  addr: localhost:6379
  password: myRedisPassword
  db: 0
