host:
  limiter: 8080
  # mode: counter(計數器)、tokenBucket(令牌桶)、redisCounter(計數器 Redis)
  mode: redisCounter
  interval: 15
  maxCount: 5

gin:
  # mode: debug、release、test
  mode: debug

redis:
  addr: localhost:6379
  password: myRedisPassword
  db: 0
